---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: mariadb-backup
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    cron: "0 2 * * *"  # Daily at 2 AM
    suspend: false
  maxRetention: 168h  # 7 days
  storage:
    persistentVolumeClaim:
      storageClassName: ceph-filesystem
      resources:
        requests:
          storage: 20Gi
      accessModes:
        - ReadWriteMany
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s-0
                  - k8s-1
                  - k8s-2
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1