# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
stringData:
  root-password: ENC[AES256_GCM,data:bDnWHR7VQQrXsLyXSssN8eAlMmXRn6MknZX2GwCVqS72Lo5V97aRQ7Svyfs=,iv:/GRDtVB78g2QX8gab6m2ycJpr3i/bOgtgp/F8TIGH2g=,tag:q8pyJpel0T6qkUc9v//v8Q==,type:str]
  erpnext-password: ENC[AES256_GCM,data:nstqdEqEGsSSvmmwZtt4tYt9jzfngVDJzAUwXZlbcP+NKopIH1R08ZWy7/U=,iv:1HqpDL6hDCEpSMeb2zYLPtg/d7ZSIdceDS5NF/lMWPw=,tag:5hj5Kfq1s+65o/V9pnDn3w==,type:str]
sops:
  age:
    - recipient: age1je98fjlwqdjlqm3wp039t6tj92plzl8y5dcaat654tlcg82g49cq3uylh4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeTdMM1dmcVFwR0E3ek1m
        cEI1QXdXLzg5YTVGYWJsN0c1MUluei83VWhjClVITGpXckl0WHZnZm1vN2NmMWEr
        MHEwUy9aUEtDUnBoZWNPZGVXZDQ1KzgKLS0tIGQ2VHRKM012TlE0OE9OMTMzdzdy
        SkZTWWdTb212Mk1xaEdKVEZ3ZE92WW8K0gmoSkcSwkhfdyUwhPJz55sV/3D1SN6q
        wVk6e2QuI+m6U52l9sRTPJvGBbI0UdkIDE/ZCN+kIANFLIWsJphg3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-18T15:02:48Z"
  mac: ENC[AES256_GCM,data:YeaMj9CFxIxUIemAWCVbd8d99nR1Zb0Jj04K1X/5nMj/n4tk1VXFA6XS8az7lojbnMbbab4N9fpwVnDKPbC3poXYP7jruwvXwEds4wGDl7xY5vz97tNd63q5Zmp0f0qUh7I1XXgFPhQ+Dg0VF31mLwK8D8rW98n+Ir7wxVk7eCI=,iv:2N52quKPwuw69R1rOs7sEHq8fUuGtk9fPRvjeGuwdSg=,tag:j1GSV2BV9j5wglcT73RSMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: erpnext-db-secret
stringData:
  root-password: ENC[AES256_GCM,data:Fwd77mqz/V/Xa7cRNxXkJ0rukPt99EOleuFvf4D6cDtUfPDG9K4WZ90cvzc=,iv:xLwkFyltFuZ53h/jJ1/6olckMzshx0C7A0QRYU/B4z4=,tag:entWi1Emh8wLNTbbYgXaJQ==,type:str]
sops:
  age:
    - recipient: age1je98fjlwqdjlqm3wp039t6tj92plzl8y5dcaat654tlcg82g49cq3uylh4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeTdMM1dmcVFwR0E3ek1m
        cEI1QXdXLzg5YTVGYWJsN0c1MUluei83VWhjClVITGpXckl0WHZnZm1vN2NmMWEr
        MHEwUy9aUEtDUnBoZWNPZGVXZDQ1KzgKLS0tIGQ2VHRKM012TlE0OE9OMTMzdzdy
        SkZTWWdTb212Mk1xaEdKVEZ3ZE92WW8K0gmoSkcSwkhfdyUwhPJz55sV/3D1SN6q
        wVk6e2QuI+m6U52l9sRTPJvGBbI0UdkIDE/ZCN+kIANFLIWsJphg3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-18T15:02:48Z"
  mac: ENC[AES256_GCM,data:YeaMj9CFxIxUIemAWCVbd8d99nR1Zb0Jj04K1X/5nMj/n4tk1VXFA6XS8az7lojbnMbbab4N9fpwVnDKPbC3poXYP7jruwvXwEds4wGDl7xY5vz97tNd63q5Zmp0f0qUh7I1XXgFPhQ+Dg0VF31mLwK8D8rW98n+Ir7wxVk7eCI=,iv:2N52quKPwuw69R1rOs7sEHq8fUuGtk9fPRvjeGuwdSg=,tag:j1GSV2BV9j5wglcT73RSMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
