---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mariadb-galera-tls
spec:
  secretName: mariadb-galera-tls
  issuerRef:
    name: mariadb-selfsigned-issuer
    kind: Issuer
  commonName: mariadb-galera.db.svc.cluster.local
  dnsNames:
    - mariadb-galera.db.svc.cluster.local
    - mariadb-galera.db.svc
    - mariadb-galera.db
    - mariadb-galera
    - "*.mariadb-galera.db.svc.cluster.local"
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days