---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-galera-secret
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mariadb-galera-secret
    template:
      engineVersion: v2
      data:
        root-password: "{{ .mariadb_root_password }}"
        mariadb-password: "{{ .mariadb_password }}"
        replication-password: "{{ .mariadb_replication_password }}"
  dataFrom:
    - extract:
        key: mariadb-galera