---
# Multipathd config - extension not working correctly in Talos v1.12
# Keeping config in case future versions fix the containerization issue
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: multipathd
configFiles:
  - content: |
      defaults {
          user_friendly_names yes
          find_multipaths no
          path_selector "round-robin 0"
          path_grouping_policy failover
          failback immediate
          no_path_retry fail
      }
      devices {
          device {
              vendor "DELL"
              product "Shared_PERC8"
              path_grouping_policy failover
              path_selector "round-robin 0"
          }
      }
    mountPath: /etc/multipath.conf
