---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: erpnext-secret
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: erpnext-secret
    template:
      engineVersion: v2
      data:
        admin-password: "{{ .erpnext_admin_password }}"
        ERPNEXT_ADMIN_PASSWORD: "{{ .erpnext_admin_password }}"
        
  dataFrom:
    - extract:
        key: erpnext