---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: z2m-b
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  dataFrom:
    - extract:
        key: zigbee2mqtt
  target:
    name: z2m-b-secrets
    creationPolicy: Owner
    template:
      data:
        mqtt_user: "{{ .MQTT_USERNAME }}"
        mqtt_password: "{{ .MQTT_PASSWORD }}"
        zigbee_network_key: "[0x59,0xD6,0x1F,0xDE,0xF5,0x1F,0x8B,0xA6,0x69,0x64,0x55,0xE1,0xDC,0x7A,0x90,0x22]"
        zigbee_pan_id: "43090"
        zigbee_ext_pan_id: "[0x87,0x4A,0x0B,0xD1,0xB5,0x46,0xE7,0x6F]"
