---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app erpnext
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  # components:
    # - ../../../../components/gatus/public  # Using custom gatus config for domain 2
    # TODO: Enable volsync after ERPNext is working
    # - ../../../../components/volsync
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: mariadb
    - name: erpnext-redis
  interval: 1h
  path: ./kubernetes/apps/frappe/erpnext/app
  postBuild:
    substitute:
      APP: *app
      GATUS_PATH: /
      GATUS_SUBDOMAIN: erp
      VOLSYNC_CAPACITY: 20Gi
      VOLSYNC_CACHE_CAPACITY: 10Gi
      VOLSYNC_SCHEDULE: "0 1,7,13,19 * * *"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: frappe
  timeout: 5m
  wait: false