---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-prod-secret
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-tunnel-prod-secret
    template:
      engineVersion: v2
      data:
        TUNNEL_TOKEN: "{{ .cloudflare_tunnel_prod_token }}"
  dataFrom:
    - extract:
        key: cloudflare-tunnel-prod