# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-prod-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:CrihcURDJBqfG/ZpAxBmzMJZ+xtmuLpZQZ+Bgua+IU80UPpr0lS9/aHAven08PQrgL6Umxfcq68csjU+6dWLQ3y40YYkUCl2dxcmPZDz91+xsdovzofnPuRm1UMwsvE6vEYoshWe69rYkmXFZ5XekGtGxFyRC1AHvRIlzQU+cdSKYtoU6hhwGQaI1EH+g7j2FnWYf3U0kWyDgATTu5S6zMzit7l/LKmgt3LgjRPWBLcKdUZF,iv:9HI8aGGgGGONGjgQ3OJzk6rwJbb3rwZIsdf8GzlOmLQ=,tag:wLmGwI3rSlnhWoIVMrKuiw==,type:str]
  CLOUDFLARE_TUNNEL_ID_PROD: ENC[AES256_GCM,data:xbEygRbd10B89Nx5ZtePYyYY17VNz34g458p0GebCnWuIwXx,iv:bRc9SFrpD3QD65a1/UvzZx+j+Jlw0m1NQ8iBqJ2NOlA=,tag:lYdG+tpVs+Zxlz2Ys4V0Ig==,type:str]
sops:
  age:
    - recipient: age1je98fjlwqdjlqm3wp039t6tj92plzl8y5dcaat654tlcg82g49cq3uylh4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMlNDSWFueGlYSFU0QmNR
        T0hHaldUeUxzZndGUmZXcHVKb2M5Qkh0cncwCmxCZkI2VzlTMXJMWFV3SmhFbXE5
        akM2Nms5bGFndnZpY3hyWGZ0RzJvK28KLS0tIDFYUFBUSHZZcXFnMzB3ZTFnZTd3
        VURncHE2K0t0UWVtN2hkRng0N0RydGMKaHIrUMfXLwqfp41qJIJWR6u1WpWnv8nB
        3PSGHSRSC1oC2P0QS/QRwjnvBS9GhCHUKvpKczHY2d9Zax/PSgefcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-03T13:23:21Z"
  mac: ENC[AES256_GCM,data:KFFevEtHsOymMLo5f4WU/l8po2mMHsEtNGhTApPPvCv/zqGsCBkLat49KxLqA+Xj0fZMT91gP7qMg8AImv6IIzoK2BvSXcBFwfM3+k6sfdAO2mPk3H29L9ddwCNIuAcSioX5KP/q6+oZLrJDqhShvQsOI7V3TnqLmX95iNdq68Q=,iv:okW+u+ashFdVGCFx3O5C9sdGFV+9fCTt99VJOcEahZk=,tag:aL6BwTzrB9VCVXjJFIrIpw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
