---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-mqtt-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: emqx-mqtt-tcp
        group: IoT
        url: tcp://emqx-listeners.iot.svc.cluster.local:1883
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
      - name: emqx-dashboard
        group: IoT
        url: https://emqx.k8s.${SECRET_DOMAIN}/status
        interval: 5m
        client:
          dns-resolver: tcp://192.168.168.1:53
        conditions:
          - "[STATUS] == 200"
          - "[BODY] == pat(*is running*)"
        alerts:
          - type: pushover
