---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: erpnext-${TENANT}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: erpnext-${TENANT}-secret
    template:
      data:
        mariadb-root-password: "{{ .MARIADB_ROOT_PASSWORD }}"
        admin-password: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: erpnext-${TENANT}
