---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: code-pod-ssh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: code-pod-ssh-secret
    template:
      data:
        authorized_keys: "{{ .AUTHORIZED_KEYS }}"
  dataFrom:
    - extract:
        key: code-pod-ssh
