---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: code-pod-tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: code-pod-tailscale-secret
    template:
      data:
        TS_AUTHKEY: "{{ .TS_OAUTH_CLIENT_SECRET }}?ephemeral=true&preauthorized=true&tags=tag:k8s"
  dataFrom:
    - extract:
        key: code-pod
