---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc-ssh-host-keys.yaml
  - ./externalsecret-tailscale.yaml
  - ./externalsecret-ssh.yaml
  - ./externalsecret-anthropic.yaml
  - ./helmrelease.yaml
  - ./workspace/pvc.yaml
  - ./workspace/replicationsource.yaml
  - ./workspace/replicationdestination.yaml
  - ./workspace/externalsecret.yaml
