lovelace:
  dashboards:
    lovelace-maximalist:
      mode: yaml
      title: Maximalist
      icon: mdi:view-dashboard-variant
      filename: hass-config-src/repo/lovelace/lovelace-maximalist.yaml
      show_in_sidebar: true
      require_admin: false
