---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: blackbox-exporter
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 8.5.0
  url: oci://registry-1.docker.io/prometheus/blackbox-exporter
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: blackbox-exporter
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: blackbox-exporter
    serviceMonitor:
      enabled: true
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            valid_status_codes: [200]
            method: GET
            preferred_ip_protocol: "ip4"
            follow_redirects: true
        http_post_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            method: POST
            preferred_ip_protocol: "ip4"
            follow_redirects: true
        icmp:
          prober: icmp
          timeout: 5s
          icmp:
            preferred_ip_protocol: "ip4"
        dns_tcp:
          prober: dns
          timeout: 5s
          dns:
            transport_protocol: "tcp"
            preferred_ip_protocol: "ip4"
            query_name: "kubernetes.default.svc.cluster.local"
            query_type: "A"
        dns_udp:
          prober: dns
          timeout: 5s
          dns:
            transport_protocol: "udp"
            preferred_ip_protocol: "ip4"
            query_name: "kubernetes.default.svc.cluster.local"
            query_type: "A"