# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:6iuYVwe7rAaCVhwOJ+gqZw1b21RrEkY5zso5IKzV2VwBoQ72pNXzxVCfevBEy2zlkOPYvZWyGjQhLQPMjpn0niwJeh9sM5zxRJb5cGKHusUL92oLMn4DBgGPBQex01uRO7TzGCKN4lHm/Sii2np9A+WPYJxQspBAofS9GaUgEZys7p6cBubbxKaX9LA21Kr0mBXivRyU/Jfi96bvj1erJuFieY53Rzth1xyOofVuxO5zkvwt,iv:wSvBm23G5sbz7femQNs8T5eDe+LPJ0mSjvLIbXRWvNI=,tag:F5l/lZd7qd0lSVqZqcP4Ug==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Piaz71Lsbr7p1rMG0dvGYEJqAHXOij698G01scjLadRIgORB,iv:mNKKJ9dNFQ3vSkTi0+DCW2TZFKgsU9jbrGFH9Ph9T6k=,tag:Bv6cHxj/mwYGC2/2MpaoJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1je98fjlwqdjlqm3wp039t6tj92plzl8y5dcaat654tlcg82g49cq3uylh4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNDkwd2NWYnZEa2xyWEMx
            OWE5cE5YZEVGclgrVFF2azhaODVTZ2ZPVGxnCjFvd1hSbTdoUnRHY1hWcnlLWTFj
            TlJNc2VrbVJmRWVxYW1BUWdpR1RobTQKLS0tIDNWcGhGcUZjcDlMRGlrUzVoOXBy
            SjhpZDBVbDUwUzMyS01FeFZ4K2swR3MKS4/WaUaVkvqIakXZoEy8RhKZA91a3mk5
            bNb7RWAxf1KpFrQrmRZTPR0PMnniSu8kpdiIEnWEo0F2am0fzmxDEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-21T05:28:40Z"
    mac: ENC[AES256_GCM,data:nKsAxAgdPsCBtWtisC27HC0Ic5I26IwVcAu3bdvWO+6wtLz3SLb5ouJuh8wBkMFRo9UZ7qX+OZ4KdQYQ0EKADiSq1gGWGFfICja28O0BmVmU6AMRXx+JA9R/GUhp0AWtGx0lRGxd8hfWlqRAfO8ifTfgmZKkg9JcvA2+guMiBTk=,iv:qZ9JISOj2lDvdXVAMZcv5ukEguq0vQ+Xyfkoo7q+nvI=,tag:ykE4TCJb3DmSiVXpYAL51A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
