---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frappe
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Applications
  - ./mariadb/app
  - ./erpnext/app
  - ./redis/app