apiVersion: v1
kind: Secret
metadata:
  name: donetick-secret
stringData:
  DT_JWT_SECRET: ENC[AES256_GCM,data:uDPlLgMLFUSKTgcRDyIwhoDU41Exj2+GE6MkBtwR/HVsG5uQXxxAD0CXsZE=,iv:Cbpmlg4/Z7HJb/IzSTHcup1zQWsLxWJhoJ8q1ICjuxM=,tag:OhCrllULxy58XiXWrVwGFw==,type:str]
  DT_SERVER_CORS_ALLOW_ORIGINS: ENC[AES256_GCM,data:Fr1LoXBv2nqsi93vnmmMrGgkHG6uk1/+vIm9EaLIrpiJN1Xg7CgLVJORP2iG79KbP2eX0UB22QLyaz0=,iv:x3rA2y9VbUJw8oGAqtFPGLBRHHurIdkgUsbcoNRQjPM=,tag:N6Nw5/gttHXAn9xPIAjtCg==,type:str]
sops:
  age:
    - recipient: age1je98fjlwqdjlqm3wp039t6tj92plzl8y5dcaat654tlcg82g49cq3uylh4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa2NVa200Z2I2ellYMkZ2
        akdXN1pmSkI1SHkrbDRybGd2L2g2QStrOUVNCjBsOWdEWWZ4cUpNWmtheVNORWN1
        dFVGY1UyNWNETzlGelh3b3hCKzNYeVkKLS0tIHdBT0ZFVU40a1c1WVB6ZzA0cFll
        eEZ6NjhNVU9IcVIraWw0NUdRWFZpdnMKgiyeFQXF34hi91enV/J30bzYWWsCl600
        DWRWIJuGerE1F1P93VaqofNlOLGe4a5HV+gNWCLrunu6Rx5hRvboYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-18T03:27:50Z"
  mac: ENC[AES256_GCM,data:6wTd9ltahEij8Qwn7+1j149bS/luvcatnc1ME6hP+M/lQj1oHZ7R+N6VQWRO+L10gwZsP4lSCU6QG01RPidPTxvZRhVWub3o0n8i6Jguk0WPhkBS2tg8K5SFKYlPmzDd95vwnfps3vAnOQuCiOIH/8P/QfMKXRSUGHmfKgi+G2U=,iv:U69Biq9jjyC9jZ38ApeM7vjkeynvkMJbg6RkGrGxM7I=,tag:9LiRyeuot0SjQyxPTtYFEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
