---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-pod-workspace
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: code-pod-workspace-dst
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-block
