---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-services
components:
  - ../../components/common
resources:
  - ./overseerr/ks.yaml
