apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:jIDPnmttryrhW8Gj,iv:qYk5mDNwH6vOu6f+T6Qi/3yv7hrWGo0A0VvQZ7K0ApY=,tag:O1yo5VrBFmUbWWBHW5w2BQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1je98fjlwqdjlqm3wp039t6tj92plzl8y5dcaat654tlcg82g49cq3uylh4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZG02WVVGUDZTTW1ZRFN2
        MVFpRjFpNThVK3M2UWtqM09LRHpPczRLUm1FCmw2aHcwSG0raTN5V2NlbFpQVnVM
        aHhYY1BoTjA5bFdKZ3kyL1ZKVjhzWDgKLS0tIHh3R3BWdjVwdXhsZ2hYWFcvTnNN
        a3hxcVprL2dBRng3clZTbCs5NDUzNU0KabeCjy3Ll8PZ4THWeMRbscoXKrB7meKx
        ffP6DF3M5Kwu4wOJCf5IIjRG+Y+cXxF0wmBga42JW11YeVmYnTiE5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-18T01:35:13Z"
  mac: ENC[AES256_GCM,data:LuY8CCqvXr4dwkuWICl1nxjfyfCDEOxbeaZKCK7tG4hxUia7MMQeaBIi+F+tuInm8Kpr0PxYVXHf+Y5DEcP4ESfiw0mWOonXiYZuI8uI/myW4JwTTrR+xCBf8rK993tY4Ru074hMg1EUI8pf1CrFVeNJlsBF3sMaZAYBV0Aa2Gw=,iv:vmg2xyI69hJmyRM7loSVNaIy7I7GHnVYuAeUkhztVhk=,tag:j/rJy6j1VmFS//TKwfNVWw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
