apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secret
stringData:
  VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:8mAxx6KXocKSfkA3qAji1EhB4JDh5i17QvJzX5KzlRJopILt/S+lzuMrkchGLhlnMolJPucRfZ6tw2pHq92waQ==,iv:BE0CbJfdka5qj3ivzPa5AwvwYiffp16TpTfVih2Ws8U=,tag:lPlm6mL0+VGOnlmRybyImg==,type:str]
sops:
  age:
    - recipient: age1je98fjlwqdjlqm3wp039t6tj92plzl8y5dcaat654tlcg82g49cq3uylh4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZkxTejhoU1JKSUNBTGw4
        YXFRSmFKZWZLVVF5bU15TE56Yjd1N1R6aEV3Ci9Db2ZPVWFod0JOa3h6MHJ6WTFB
        TGx0UUdtWlhnNFVTM01yS0dnbjlEcWcKLS0tIGZMTW5qN0VZMDlOQVhZSngwMFo0
        MHdyTUR4ZUI4QzZIbXFPSzVxL0U4YWcKebGsLOwfdrngOMrGkHGEeUSYKEa7SMVo
        Du/Q0H4qx9bwOFtGCh8xDQ5hLQo3XKUSDokvPGevxJFAKHVsa8aaMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T23:54:58Z"
  mac: ENC[AES256_GCM,data:Z/hPxWTI6hx4BbDGNRGAArn90y7T6yG9+x6msQx/Ce/CJ0nt55JdSWyxxZyARDEervyp37ibtrS/PuQC/WsJyAYb2E5KMXO87Nr1x0DI58chzt53iFt9wziNELQUQTWeGhFNO79esFjJ1mA3dvT80v5KLFt2qFDRcu2Wlszd50s=,iv:tL5B0tqsh664hXHOkQx3O3NtEd3ay6gfsCi0LvVwep4=,tag:D6SKFT/1U+FsfnYfBpa3mw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
