---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: app-template
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: main
  url: oci://ghcr.io/bjw-s/helm-charts/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpoller
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      unpoller:
        containers:
          app:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v2.14.1
            env:
              TZ: America/New_York
              UP_UNIFI_DEFAULT_ROLE: vrtx-cluster
              UP_UNIFI_DEFAULT_URL: https://192.168.1.1
              UP_PROMETHEUS_HTTP_LISTEN: 0.0.0.0:80
              UP_INFLUXDB_DISABLE: true
            envFrom:
              - secretRef:
                  name: unpoller-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      app:
        controller: unpoller
        ports:
          http:
            port: 80
    serviceMonitor:
      app:
        serviceName: unpoller
        endpoints:
          - port: http
            interval: 2m # Unifi API only polls at 2m intervals
            scrapeTimeout: 10s