homeassistant:
  enabled: true
advanced:
  network_key:
    - 89
    - 214
    - 31
    - 222
    - 245
    - 31
    - 139
    - 166
    - 105
    - 100
    - 85
    - 225
    - 220
    - 122
    - 144
    - 34
  pan_id: 43090
  ext_pan_id:
    - 135
    - 74
    - 11
    - 209
    - 181
    - 70
    - 231
    - 111
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  transmit_power: 20
  channel: 25
  log_level: warning
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: ioJiinaeTh0aZie4Ohph7ahgo9zohgooye0shoo5quoh9ahyaiju5yei2pikei5w
  keepalive: 60
  reject_unauthorized: true
  version: 4
  base_topic: z2m-haos
serial:
  port: tcp://192.168.252.251:6638
  adapter: zstack
  baudrate: 460800
frontend:
  enabled: true
  port: 8099
device_options: {}
devices:
  '0x040d84fffe02afbd':
    friendly_name: Laundry Room Dimmer
  '0x943469fffe088f0d':
    friendly_name: Albert's Bedroom Dimmer
  '0x943469fffe089598':
    friendly_name: Aude's Bedroom Dimmer
  '0xa4c13883f243975b':
    friendly_name: Laundry Room Door Downlight
  '0xa4c1382a9416d096':
    friendly_name: Laundry Room Downlight 1
  '0xa4c138def9af821a':
    friendly_name: Aude's Bedroom Door Downlight
  '0xa4c1388070db87c6':
    friendly_name: Laundry Room Downlight 2
  '0xa4c138a33a3af6e1':
    friendly_name: Albert's Bedroom Door Downlight
  '0xa4c138de62fd3df0':
    friendly_name: Basement Corridor Downlight 5
  '0xa4c138bd19ab7e9b':
    friendly_name: Family Room Downlight Left
  '0xa4c1387a5ae87781':
    friendly_name: Basement Corridor Downlight 1
  '0xa4c13880e0a44e1c':
    friendly_name: Aude's Bedroom Window Downight
  '0xa4c1386c67e66918':
    friendly_name: Basement Corridor Downlight 4
  '0xa4c138c9e4a2c676':
    friendly_name: Family Room Downlight Middle
  '0xa4c138df3e652793':
    friendly_name: Basement Corridor Downlight 2
  '0xa4c13875796b55d9':
    friendly_name: Basement Corridor Downlight 3
  '0xa4c138d461d31ae2':
    friendly_name: Basement Corridor Downlight 6
  '0xa4c138519f1c7362':
    friendly_name: Basement Corridor Downlight 7
  '0xa4c1380fecd03eb7':
    friendly_name: Family Room Downlight Right
  '0xa4c1388d2ec891ab':
    friendly_name: Basement Corridor Downlight 8
  '0xa4c13838963c2d2b':
    friendly_name: Albert's Bedroom Wall Downlight
  '0x8c6fb9fffe3c75a9':
    friendly_name: Laundry Room Motion
  '0x00124b00250ba254':
    friendly_name: Aude's bedroom THS
    temperature_calibration: ''
  '0x040d84fffe0601f3':
    friendly_name: Family Room Dimmer
  '0x00124b002512f842':
    friendly_name: Albert's Bedroom THS
    temperature_precision: 2
    humidity_calibration: 0
    humidity_precision: 2
    temperature_calibration: 0
  '0x287681fffed5a5af':
    friendly_name: Family Room AQS
  '0xec1bbdfffef6212b':
    friendly_name: 'Albert''s Bedroom String lights '
  '0xdc8e95fffee3e494':
    friendly_name: Basement Air purifier
  '0x282c02bfffe7683a':
    friendly_name: Laundry room Door
  '0xf44250c392060000':
    friendly_name: Basement Night Light
    illuminance_calibration: 0
    transition: 1
    color_sync: true
    state_action: true
  '0x282c02bfffe8009c':
    friendly_name: Server Room Motion
  '0xa4c138d17963fec8':
    friendly_name: Rack LEDs
groups:
  '1':
    friendly_name: z2m_laundry_room_downlights
  '2':
    friendly_name: z2m_aude_s_bedroom_downlights
  '3':
    friendly_name: z2m_albert_s_bedroom_downlights
  '4':
    friendly_name: z2m_family_room_downlights
  '5':
    friendly_name: z2m_basement_corridor_downlights
availability:
  enabled: true
version: 4
