---
apiVersion: v1
kind: Secret
metadata:
    name: homebox-secret
stringData:
    HBOX_OAUTH_OIDC_URL: ""
    HBOX_OAUTH_OIDC_CLIENT_ID: ""
    HBOX_OAUTH_OIDC_CLIENT_SECRET: ""
    HBOX_OAUTH_OIDC_SERVER_ID: ""
    # yamllint disable-line rule:line-length
    HBOX_OAUTH_OIDC_REDIRECT_URL: https://homebox.k8s.${SECRET_DOMAIN}/auth/oidc/callback
