---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: home-assistant-lovelace-maximalist
    files:
      - lovelace_maximalist.yaml=./resources/lovelace_maximalist.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
postBuild:
  substituteFrom:
    - kind: Secret
      name: cluster-secrets
