endpoints:
  - name: "${APP}"
    group: Internal Services
    url: 1.1.1.1
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    dns:
      query-name: "${GATUS_SUBDOMAIN:=${APP}}.k8s.${SECRET_DOMAIN}"
      query-type: A
    conditions:
      - "len([BODY]) == 0"
