endpoints:
  - name: "${APP}"
    group: Internal Services
    url: "https://${GATUS_SUBDOMAIN:-${APP}}.k8s.mstrsmth.io${GATUS_PATH:-/}"
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    conditions:
      - "len([BODY]) != 0"
      - "[STATUS] == ${GATUS_STATUS:=200}"
